version: '3'
services:
  app:
    build: .
    ports:
      - "9876:9876"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/purple-pay
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
